-- ============================================================================
--  queries.sql — SQL query showcase (Coffee & Cotton market-risk demo)
--
--  Source: data/commodities.db (SQLite), generated by pipeline.py from real ICE
--  futures prices. Demonstrates JOINs, aggregation, date parsing, CASE logic
--  and window functions over a real financial dataset.
--
--  How to run:
--    sqlite3 data/commodities.db ".read queries.sql"
--    -- or open each query in DB Browser for SQLite.
--
--  Tables: prices, daily_metrics, correlation, kpi_snapshot
--  View:   v_latest_risk
-- ============================================================================


-- ----------------------------------------------------------------------------
-- Q1. Latest-session risk snapshot (JOIN + correlated subquery).
--     "Where are we NOW?" — price, vol and flag per commodity.
-- ----------------------------------------------------------------------------
SELECT ticker, commodity, date,
       ROUND(close, 2)            AS close,
       ROUND(vol_21d * 100, 1)    AS vol_annual_pct,
       ROUND(drawdown * 100, 1)   AS drawdown_pct,
       risk_flag
FROM   v_latest_risk
ORDER  BY vol_21d DESC;


-- ----------------------------------------------------------------------------
-- Q2. Top 10 largest daily drops in coffee (filter + ORDER BY + LIMIT).
--     Useful to investigate market shocks (frost in Brazil, etc.).
-- ----------------------------------------------------------------------------
SELECT m.date, ROUND(p.close, 2) AS close, ROUND(m.ret_pct, 2) AS change_pct
FROM   daily_metrics m
JOIN   prices p ON p.ticker = m.ticker AND p.date = m.date
WHERE  m.ticker = 'KC=F'
ORDER  BY m.ret_pct ASC
LIMIT  10;


-- ----------------------------------------------------------------------------
-- Q3. Days a risk limit was breached (BREACH), by month.
--     Time aggregation — how many high-risk sessions per month.
-- ----------------------------------------------------------------------------
SELECT ticker,
       substr(date, 1, 7)  AS month,
       COUNT(*)            AS days_in_breach
FROM   daily_metrics
WHERE  risk_flag = 'BREACH'
GROUP  BY ticker, month
ORDER  BY month DESC, ticker;


-- ----------------------------------------------------------------------------
-- Q4. Average annualized volatility per commodity and per year (GROUP BY + AVG).
--     Compares the "risk level" of coffee vs cotton over time.
-- ----------------------------------------------------------------------------
SELECT ticker,
       substr(date, 1, 4)              AS year,
       ROUND(AVG(vol_21d) * 100, 1)    AS vol_avg_pct,
       ROUND(MAX(vol_21d) * 100, 1)    AS vol_max_pct
FROM   daily_metrics
WHERE  vol_21d IS NOT NULL
GROUP  BY ticker, year
ORDER  BY year, ticker;


-- ----------------------------------------------------------------------------
-- Q5. Price statistics per commodity (MIN/MAX/AVG + range).
--     3-year range — a basis for sizing exposure and margin.
-- ----------------------------------------------------------------------------
SELECT p.commodity,
       COUNT(*)                              AS sessions,
       ROUND(MIN(close), 2)                  AS minimum,
       ROUND(AVG(close), 2)                  AS average,
       ROUND(MAX(close), 2)                  AS maximum,
       ROUND(MAX(close) - MIN(close), 2)     AS range
FROM   prices p
GROUP  BY p.commodity;


-- ----------------------------------------------------------------------------
-- Q6. Maximum drawdown (worst peak-to-trough loss) per commodity.
--     Classic risk KPI: how far the asset has fallen from its peak.
-- ----------------------------------------------------------------------------
SELECT ticker,
       ROUND(MIN(drawdown) * 100, 1) AS max_drawdown_pct
FROM   daily_metrics
GROUP  BY ticker
ORDER  BY max_drawdown_pct;


-- ----------------------------------------------------------------------------
-- Q7. Trend signal (moving-average crossover) at the latest session.
--     CASE WHEN — "golden cross" (MA50 > MA200) vs "death cross".
-- ----------------------------------------------------------------------------
SELECT m.ticker, p.date,
       ROUND(m.ma50, 2)  AS ma50,
       ROUND(m.ma200, 2) AS ma200,
       CASE WHEN m.ma50 >= m.ma200 THEN 'Uptrend (golden cross)'
            ELSE 'Downtrend (death cross)'
       END AS signal
FROM   daily_metrics m
JOIN   prices p ON p.ticker = m.ticker AND p.date = m.date
WHERE  p.date = (SELECT MAX(date) FROM prices)
  AND  m.ma200 IS NOT NULL;


-- ----------------------------------------------------------------------------
-- Q8. Average coffee × cotton correlation per year (portfolio diversification).
--     Low correlation = risk more diversified across the two legs.
-- ----------------------------------------------------------------------------
SELECT substr(date, 1, 4)            AS year,
       ROUND(AVG(corr_63d), 2)       AS avg_correlation,
       COUNT(*)                      AS observations
FROM   correlation
GROUP  BY year
ORDER  BY year;


-- ----------------------------------------------------------------------------
-- Q9. Coffee seasonality: average return by month (date parsing + GROUP BY).
--     A seasonal pattern helps anticipate risk/opportunity windows.
-- ----------------------------------------------------------------------------
SELECT substr(date, 6, 2)           AS month,
       ROUND(AVG(ret_pct), 2)       AS avg_return_pct,
       COUNT(*)                     AS days
FROM   daily_metrics
WHERE  ticker = 'KC=F' AND ret_pct IS NOT NULL
GROUP  BY month
ORDER  BY avg_return_pct DESC;


-- ----------------------------------------------------------------------------
-- Q10. Window function: price vs. 20-session moving average computed in SQL.
--      Demonstrates analytic SQL (AVG OVER) without relying on Python.
-- ----------------------------------------------------------------------------
SELECT ticker, date, ROUND(close, 2) AS close,
       ROUND(AVG(close) OVER (
           PARTITION BY ticker ORDER BY date
           ROWS BETWEEN 19 PRECEDING AND CURRENT ROW), 2) AS moving_avg_20d
FROM   prices
WHERE  ticker = 'KC=F'
ORDER  BY date DESC
LIMIT  15;
