/// Latest-session snapshot, one row per commodity — the pre-computed KPIs the
/// pipeline emits. Handy for card visuals without writing DAX. Loaded from
/// data/kpi_snapshot.csv.
table KPI_Snapshot
	lineageTag: a3000000-0000-0000-0000-0000000000f3

	column ticker
		dataType: string
		lineageTag: a3000000-0000-0000-0000-000000000001
		summarizeBy: none
		sourceColumn: ticker

		annotation SummarizationSetBy = Automatic

	column commodity
		dataType: string
		lineageTag: a3000000-0000-0000-0000-000000000002
		summarizeBy: none
		sourceColumn: commodity

		annotation SummarizationSetBy = Automatic

	column commodity_pt
		dataType: string
		lineageTag: a3000000-0000-0000-0000-000000000003
		summarizeBy: none
		sourceColumn: commodity_pt

		annotation SummarizationSetBy = Automatic

	column unit
		dataType: string
		lineageTag: a3000000-0000-0000-0000-000000000004
		summarizeBy: none
		sourceColumn: unit

		annotation SummarizationSetBy = Automatic

	column exchange
		dataType: string
		lineageTag: a3000000-0000-0000-0000-000000000005
		summarizeBy: none
		sourceColumn: exchange

		annotation SummarizationSetBy = Automatic

	column contract_lbs
		dataType: int64
		formatString: #,0
		lineageTag: a3000000-0000-0000-0000-000000000006
		summarizeBy: none
		sourceColumn: contract_lbs

		annotation SummarizationSetBy = Automatic

	column last_date
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: a3000000-0000-0000-0000-000000000007
		summarizeBy: none
		sourceColumn: last_date

		annotation SummarizationSetBy = Automatic

	column last_close
		dataType: double
		formatString: 0.00
		lineageTag: a3000000-0000-0000-0000-000000000008
		summarizeBy: none
		sourceColumn: last_close

		annotation SummarizationSetBy = Automatic

	column day_change_pct
		dataType: double
		formatString: 0.00
		lineageTag: a3000000-0000-0000-0000-000000000009
		summarizeBy: none
		sourceColumn: day_change_pct

		annotation SummarizationSetBy = Automatic

	column vol_21d_annual_pct
		dataType: double
		formatString: 0.0
		lineageTag: a3000000-0000-0000-0000-00000000000a
		summarizeBy: none
		sourceColumn: vol_21d_annual_pct

		annotation SummarizationSetBy = Automatic

	column drawdown_pct
		dataType: double
		formatString: 0.0
		lineageTag: a3000000-0000-0000-0000-00000000000b
		summarizeBy: none
		sourceColumn: drawdown_pct

		annotation SummarizationSetBy = Automatic

	column pct_from_high_pct
		dataType: double
		formatString: 0.0
		lineageTag: a3000000-0000-0000-0000-00000000000c
		summarizeBy: none
		sourceColumn: pct_from_high_pct

		annotation SummarizationSetBy = Automatic

	column high_52w
		dataType: double
		formatString: 0.00
		lineageTag: a3000000-0000-0000-0000-00000000000d
		summarizeBy: none
		sourceColumn: high_52w

		annotation SummarizationSetBy = Automatic

	column low_52w
		dataType: double
		formatString: 0.00
		lineageTag: a3000000-0000-0000-0000-00000000000e
		summarizeBy: none
		sourceColumn: low_52w

		annotation SummarizationSetBy = Automatic

	column risk_flag
		dataType: string
		lineageTag: a3000000-0000-0000-0000-00000000000f
		summarizeBy: none
		sourceColumn: risk_flag

		annotation SummarizationSetBy = Automatic

	column contract_notional_usd
		dataType: double
		formatString: #,0
		lineageTag: a3000000-0000-0000-0000-000000000010
		summarizeBy: none
		sourceColumn: contract_notional_usd

		annotation SummarizationSetBy = Automatic

	column corr_coffee_cotton_63d
		dataType: double
		formatString: 0.00
		lineageTag: a3000000-0000-0000-0000-000000000011
		summarizeBy: none
		sourceColumn: corr_coffee_cotton_63d

		annotation SummarizationSetBy = Automatic

	partition KPI_Snapshot = m
		mode: import
		source = ```
				let
				    Source = Csv.Document(File.Contents(DataFolder & "kpi_snapshot.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Headers, {
				        {"ticker", type text}, {"commodity", type text}, {"commodity_pt", type text},
				        {"unit", type text}, {"exchange", type text}, {"contract_lbs", Int64.Type},
				        {"last_date", type date}, {"last_close", type number}, {"day_change_pct", type number},
				        {"vol_21d_annual_pct", type number}, {"drawdown_pct", type number},
				        {"pct_from_high_pct", type number}, {"high_52w", type number}, {"low_52w", type number},
				        {"risk_flag", type text}, {"contract_notional_usd", type number},
				        {"corr_coffee_cotton_63d", type number}
				    })
				in
				    Typed
				```
