/// Fact table — one row per commodity per trading day, with prices and the
/// risk metrics pre-computed by the Python ETL (pipeline.py). Loaded from
/// data/prices.csv.
table Prices
	lineageTag: a1000000-0000-0000-0000-0000000000f1

	column date
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: a1000000-0000-0000-0000-000000000001
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

	column ticker
		dataType: string
		lineageTag: a1000000-0000-0000-0000-000000000002
		summarizeBy: none
		sourceColumn: ticker

		annotation SummarizationSetBy = Automatic

	column commodity
		dataType: string
		lineageTag: a1000000-0000-0000-0000-000000000003
		summarizeBy: none
		sourceColumn: commodity

		annotation SummarizationSetBy = Automatic

	column open
		dataType: double
		formatString: 0.00
		lineageTag: a1000000-0000-0000-0000-000000000004
		summarizeBy: none
		sourceColumn: open

		annotation SummarizationSetBy = Automatic

	column high
		dataType: double
		formatString: 0.00
		lineageTag: a1000000-0000-0000-0000-000000000005
		summarizeBy: none
		sourceColumn: high

		annotation SummarizationSetBy = Automatic

	column low
		dataType: double
		formatString: 0.00
		lineageTag: a1000000-0000-0000-0000-000000000006
		summarizeBy: none
		sourceColumn: low

		annotation SummarizationSetBy = Automatic

	column close
		dataType: double
		formatString: 0.00
		lineageTag: a1000000-0000-0000-0000-000000000007
		summarizeBy: none
		sourceColumn: close

		annotation SummarizationSetBy = Automatic

	column volume
		dataType: int64
		formatString: #,0
		lineageTag: a1000000-0000-0000-0000-000000000008
		summarizeBy: none
		sourceColumn: volume

		annotation SummarizationSetBy = Automatic

	column ret_pct
		dataType: double
		formatString: 0.00
		lineageTag: a1000000-0000-0000-0000-000000000009
		summarizeBy: none
		sourceColumn: ret_pct

		annotation SummarizationSetBy = Automatic

	column vol_21d
		dataType: double
		formatString: 0.0%
		lineageTag: a1000000-0000-0000-0000-00000000000a
		summarizeBy: none
		sourceColumn: vol_21d

		annotation SummarizationSetBy = Automatic

	column drawdown
		dataType: double
		formatString: 0.0%
		lineageTag: a1000000-0000-0000-0000-00000000000b
		summarizeBy: none
		sourceColumn: drawdown

		annotation SummarizationSetBy = Automatic

	column pct_from_high
		dataType: double
		formatString: 0.0%
		lineageTag: a1000000-0000-0000-0000-00000000000c
		summarizeBy: none
		sourceColumn: pct_from_high

		annotation SummarizationSetBy = Automatic

	column ma50
		dataType: double
		formatString: 0.00
		lineageTag: a1000000-0000-0000-0000-00000000000d
		summarizeBy: none
		sourceColumn: ma50

		annotation SummarizationSetBy = Automatic

	column ma200
		dataType: double
		formatString: 0.00
		lineageTag: a1000000-0000-0000-0000-00000000000e
		summarizeBy: none
		sourceColumn: ma200

		annotation SummarizationSetBy = Automatic

	column risk_flag
		dataType: string
		lineageTag: a1000000-0000-0000-0000-00000000000f
		summarizeBy: none
		sourceColumn: risk_flag

		annotation SummarizationSetBy = Automatic

	partition Prices = m
		mode: import
		source = ```
				let
				    Source = Csv.Document(File.Contents(DataFolder & "prices.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Headers, {
				        {"date", type date}, {"ticker", type text}, {"commodity", type text},
				        {"open", type number}, {"high", type number}, {"low", type number},
				        {"close", type number}, {"volume", Int64.Type}, {"ret_pct", type number},
				        {"vol_21d", type number}, {"drawdown", type number}, {"pct_from_high", type number},
				        {"ma50", type number}, {"ma200", type number}, {"risk_flag", type text}
				    })
				in
				    Typed
				```
